export default{
    products: [
        {
            _id:'1',
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/s2.jpg',
            price: 1450,
            brand: 'Top-Ten',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name: 'T Shirt',
            category: 'Shirts',
            image: '/images/tsv1.jpg',
            price: 850,
            brand: 'Top-Ten',
            rating: 4.5,
            numReviews: 9,
            countInStock: 6,
        },
        {
            _id:'3',
            name: 'Jeans Pants',
            category: 'Pants',
            image: '/images/jp2.jpg',
            price: 1999,
            brand: 'Top-Ten',
            rating: 4.5,
            numReviews: 8,
            countInStock: 0,
        },
        {
            _id:'4',
            name: 'Gabardine pants',
            category: 'Pants',
            image: '/images/gp1.jpg',
            price: 1299,
            brand: 'Top-Ten',
            rating: 4,
            numReviews: 10,
            countInStock: 6,
        },   
    ]
}